-

diff --git a/.github/workflows/docker-compose-prod-185.221.213.245.yml b/.github/workflows/docker-compose-prod-185.221.213.245.yml
--- a/.github/workflows/docker-compose-prod-185.221.213.245.yml
+++ b/.github/workflows/docker-compose-prod-185.221.213.245.yml
@@ -1,6 +1,8 @@
 name: docker-compose-prod-185.221.213.245
 on: workflow_dispatch
 
+# https://github.com/petrochenkov-ak-lab/.github/settings/secrets/actions
+# IP_185_221_213_245_SSH_KEY ~/.ssh/keys/185.221.213.245/{user}
 jobs:
   validate-secrets:
     runs-on: ubuntu-latest
@@ -8,17 +10,14 @@ jobs:
       - name: Check server secrets
         env:
           KEY: ${{ secrets.IP_185_221_213_245_SSH_KEY }}
-          USER: ${{ secrets.IP_185_221_213_245_SSH_USER }}
-          HOST: ${{ secrets.IP_185_221_213_245_SSH_HOST }}
         run: |
-          [ -n "$KEY" ]  || { echo "ERROR: Secret IP_185_221_213_245_SSH_KEY is empty or not found!"; exit 1; }
-          [ -n "$USER" ] || { echo "ERROR: Secret IP_185_221_213_245_SSH_USER is empty or not found!"; exit 1; }
-          [ -n "$HOST" ] || { echo "ERROR: Secret IP_185_221_213_245_SSH_HOST is empty or not found!"; exit 1; }
+          [ -n "$KEY" ] || { echo "ERROR: Secret IP_185_221_213_245_SSH_KEY is empty or not found!"; exit 1; }
           echo "SUCCESS: All secrets for 185.221.213.245 are valid."
 
   run-deploy:
     uses: ./.github/workflows/docker-compose-prod.yml
+    with:
+      SSH_HOST: '185.221.213.245'
+      SSH_USER: user2845bb32d13551897dd1f814
     secrets:
       SSH_KEY: ${{ secrets.IP_185_221_213_245_SSH_KEY }}
-      SSH_USER: ${{ secrets.IP_185_221_213_245_SSH_USER }}
-      SSH_HOST: ${{ secrets.IP_185_221_213_245_SSH_HOST }}
